spring:
  profiles:
    active: test

server:
  port: 8011

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

ignore:
  urls:
    - /*.html
    - /favicon.ico
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /user/login
    - /user/register
    - /user/code/*

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bingbing_paper?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  config:
    activate:
      on-profile: test

---
spring:
  datasource:
    url: jdbc:mysql://121.41.95.75:3306/bingbing_paper?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: blueSky0110.
  redis:
    host: 121.41.95.75
    database: 0
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  config:
    activate:
      on-profile: dev
